apiVersion: appstudio.redhat.com/v1beta1
kind: IntegrationTestScenario
metadata:
  name: segment-bridge-enterprise-contract
  namespace: rhtap-o11y-tenant
spec:
  application: segment-bridge
  contexts:
    - description: Application testing
      name: application
  resolverRef:
    params:
      - name: url
        value: 'https://github.com/redhat-appstudio/build-definitions'
      - name: revision
        value: main
      - name: pathInRepo
        value: pipelines/enterprise-contract-redhat-no-hermetic.yaml
    resolver: git
---
apiVersion: appstudio.redhat.com/v1beta1
kind: IntegrationTestScenario
metadata:
  name: o11y-enterprise-contract
  namespace: rhtap-o11y-tenant
spec:
  application: o11y
  contexts:
    - description: Application testing
      name: application
  configuration:
    exclude:
      # Because o11y includes a custom task in it's build pipelines in order to run unit
      # tests. That should be fine, but EC complains about it today. Grant this exception until EC
      # can learn to tolerate it.
      # https://issues.redhat.com/browse/RHTAP-1707
      - 'attestation_task_bundle.task_ref_bundles_acceptable'
  resolverRef:
    params:
      - name: url
        value: 'https://github.com/redhat-appstudio/build-definitions'
      - name: revision
        value: main
      - name: pathInRepo
        value: pipelines/enterprise-contract-redhat-no-hermetic.yaml
    resolver: git
